apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-yolo5-prod
data:
  BUCKET_NAME: tf-maayana-images-bucket-prod
  SQS_QUEUE_NAME: tf-maayana-project-queue-prod
  REGION_NAME: eu-north-1
  DYNAMODB_TABLE: tf-maayana-predictions-dynamodb-table-prod
  POLYBOT_URL: http://polybot-service.prod.svc.cluster.local:8443