apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5
  labels:
    app: yolo5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
        labels:
          app: yolo5
    spec:
      containers:
      - name: server
        image: maayanassraf/yolo5-aws-project:latest
        envFrom:
          - configMapRef:
              name: configmap-yolo5-prod
