apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5
  labels:
    app: yolo5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
        labels:
          app: yolo5
    spec:
      containers:
      - name: server
        image: maayanassraf/yolo5-aws-project:latest
        env:
          - name: BUCKET_NAME
            value: tf-maayana-images-bucket-dev
          - name: SQS_QUEUE_NAME
            value: tf-maayana-project-queue-dev
          - name: REGION_NAME
            value: eu-north-1
          - name: DYNAMODB_TABLE
            value: tf-maayana-predictions-dynamodb-table-dev
          - name: POLYBOT_URL
            value: http://polybot-service.dev.svc.cluster.local:8443
---
apiVersion: v1
kind: Service
metadata:
  name: yolo5-service
spec:
  selector:
    app: yolo5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
