apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-yolo5-dev
data:
  BUCKET_NAME: tf-maayana-images-bucket-dev
  SQS_QUEUE_NAME: tf-maayana-project-queue-dev
  REGION_NAME: eu-north-1
  DYNAMODB_TABLE: tf-maayana-predictions-dynamodb-table-dev
  POLYBOT_URL: http://polybot-service.dev.svc.cluster.local:8443